language: java

jdk:
- oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: hekonsek-github
    token:
      secure: "Xuxj4IwmJ+ZV90ARR0ej2MF3AB+Uptphci3eoDhnVSDkxDyEiTyJWdOGs9aW+y5T0nfuxqSa88jUNvF8WYtSDJylxShgjVY8BbpZCW0kebYsXbM1Eul6WpCS2ceKo2d5kWtN9pO0R0aK4oGT37FGuLfdnl6iI63jVng9qEOhFlih7YHrjJ/OcXKZEAMxtXjTlCtT7olrdFOezolFUAWVNffArGPMUwCXU3I7YSxXR3ZCYSeWrdQDK6K4RA8IzP998okSRSPfWYU0r6OevSDAhGvKjDK4XfPf8+vEI6LDKBcRzUhgo/SoHFFqW0uAifKzPaE8Je8rpC5nH+xbMPCqx8+XZUlPhLI07BWBfXfn4T+r2J9pJLrGw8M+d7zY3x8H5CuxW4NuxhcFrYmaLrDWKKAJRCeBZAWugtl+uxSqwu7vWZl1uqrwHt8t43PYMQURV6TI/KtRKTbj9GkuD6Ies/lPXCGQSUXPXBP8EccjWBrsy914C53J1WsBendZjZAl3iTbVq7Z7Ywefn9TH/QuVCA7JIU1n1/9H5Z3Kdh3uhAF1tnO2V8h6H70RvNdMN42SPq6/Nt/UKDBV09YKf/3V818u13wFZlcR+cgpvRLzWutRKDmb1OKluRt2+uBRN5NpynFvLLHNanlTT47am31zi5fFyHFh/meOsY/gTfOqII="

script:
  - mvn clean install sonar:sonar -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)